# Generated by Django 3.2.8 on 2021-12-24 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='产品名称')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.customgroup')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
